const GAMES_INTERACTIVE_DROPDOWN_ID_PREFIX = 'GamesDropdown';
const GAMES_INTERACTIVE_REFRESH_BUTTON_ID_PREFIX = 'GamesRefreshButton';

export default () => {
    return {
        GAMES_INTERACTIVE_DROPDOWN_ID_PREFIX,
        GAMES_INTERACTIVE_REFRESH_BUTTON_ID_PREFIX
    }
}