name: Bot restart

on:
  push:
    branches:
      - main

jobs:
  send_post_request:
    name: Send POST request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install httpie
        run: sudo apt-get install httpie

      - name: Create request body file
        run: |
          echo '{"signal": "restart"}' > request.json

      - name: Send POST request
        run: |
          http --json POST \
            ${{secrets.POWER_ENDPOINT_URL}} \
            Authorization:"${{secrets.API_KEY}}" \
            < request.json
